### ISSUE TITLE
Inconsistency in the Helm README.md

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [wso2/kubernetes-sp#20]
**Description:**
In the `README.md` of `pattern-distributed`, it is requested to provide an NFS location for field `locationPath` in `<HELM_HOME>/pattern-distributed-conf/values.yaml` file. But the above file doesnot have such a field.

**Affected Product Version:**
WSO2 Stream Processor v4.2.x

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-sp/pull/23. Hence, closing.
