### ISSUE TITLE
Deploy wso2-sp helm charts in one go

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [wso2/kubernetes-sp#21]
**Description:**
The current deployment needs to run two `helm install` commands to deploy `wso2-sp` in a kubernetes cluster. This needs to be changed so that `wso2-sp` can be deployed from one `helm install` command.

**Affected Product Version:**
WSO2 Stream Processor v4.2.x

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-sp/pull/23. Hence, closing.
